// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Marcos Quiroga Rodriguez

// Ported from alas/config/geometry_config.py (`FuselageConfig`)
// Reference: alas @ rust-port-baseline.

//! The fuselage, as the stations its surface is lofted through.
//!
//! Total length is a design variable; what is here is how that length is
//! divided and how the body is shaped along it, where the nose taper ends,
//! how long the tailcone is, and how far the nose and tail tips sit off the
//! centerline. Those three vertical offsets are what give the body its droop
//! and its tail upsweep, which is ground clearance at rotation rather than
//! decoration.
//!
//! Diameter is the one field here that a second discipline reads: the cabin
//! layout takes its usable width from it, so a change made for drag reasons
//! shows up as a seat abreast gained or lost.

use serde::{Deserialize, Serialize};

use crate::ConfigNode;

/// An additional user-controlled fuselage section at a normalized X station.
///
/// Width and height are full dimensions in metres. `shape` is the
/// superellipse exponent used by the geometry model; values at or above one
/// keep the cross-section finite and convex for the supported model.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct FuselageSection {
    /// Position along the total fuselage length, strictly inside `(0, 1)`.
    pub x_fraction: f64,
    /// Full local width, in metres.
    pub width_m: f64,
    /// Full local height, in metres.
    pub height_m: f64,
    /// Local centreline vertical offset, in metres.
    pub z_m: f64,
    /// Superellipse exponent used for this section.
    pub shape: f64,
}

/// Why a user-defined fuselage section cannot be lofted safely.
#[derive(Debug, Clone, Copy, PartialEq, thiserror::Error)]
pub enum FuselageSectionError {
    /// The generated-station override list must retain one row for every
    /// generated nose/cabin/tail station so the builder can address rows by
    /// stable station index.
    #[error(
        "generated fuselage section overrides must contain exactly {expected} stations, got {actual}"
    )]
    GeneratedSectionCount {
        /// Number of generated stations emitted by the parametric body.
        expected: usize,
        /// Number of rows supplied by the configuration.
        actual: usize,
    },
    /// A geometric field is not finite.
    #[error("custom fuselage section {index} field {field} must be finite, got {value}")]
    NonFinite {
        /// Zero-based section index.
        index: usize,
        /// Field name.
        field: &'static str,
        /// Invalid value.
        value: f64,
    },
    /// A width or height is zero or negative.
    #[error("custom fuselage section {index} {field} must be positive, got {value}")]
    NonPositive {
        /// Zero-based section index.
        index: usize,
        /// Field name.
        field: &'static str,
        /// Invalid dimension.
        value: f64,
    },
    /// The section is at an endpoint already owned by the generated body.
    #[error("custom fuselage section {index} x fraction must lie strictly in (0, 1), got {value}")]
    XOutOfRange {
        /// Zero-based section index.
        index: usize,
        /// Invalid normalized X station.
        value: f64,
    },
    /// Sections must be supplied nose-to-tail.
    #[error("custom fuselage sections must have strictly increasing x fractions; section {index} has {current} after {previous}")]
    InvalidOrder {
        /// Zero-based section index of the later station.
        index: usize,
        /// Previous normalized X station.
        previous: f64,
        /// Current normalized X station.
        current: f64,
    },
    /// The supported superellipse model does not accept this exponent.
    #[error(
        "custom fuselage section {index} shape must be finite and within [1, 50], got {value}"
    )]
    InvalidShape {
        /// Zero-based section index.
        index: usize,
        /// Invalid exponent.
        value: f64,
    },
    /// The section would share an X station with one generated by the body.
    #[error("custom fuselage section at x fraction {x_fraction} duplicates a generated station")]
    DuplicateGeneratedStation {
        /// Duplicate normalized X station.
        x_fraction: f64,
    },
}

/// Fuselage body-of-revolution or ovoid stations.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ConfigNode)]
#[serde(deny_unknown_fields)]
pub struct FuselageConfig {
    /// The widest cross-section, which sets cabin width and wetted area.
    #[config(
        label = "Fuselage diameter (width)",
        unit = "m",
        help = "Maximum fuselage cross-sectional diameter: the main driver of cabin width and wetted area. Best judged on the 3-view preview's front/isometric panels, not the top view."
    )]
    pub diameter_m: f64,

    /// The vertical dimension, or unset for a circular section.
    #[config(
        label = "Fuselage height (if non-circular)",
        unit = "m",
        help = "Vertical cross-section dimension. Leave blank/none for a circular fuselage where height equals diameter."
    )]
    pub height_m: Option<f64>,

    /// How far the nose tip droops below the centerline.
    #[config(
        label = "Nose vertical offset",
        unit = "m",
        help = "Vertical offset of the nose tip relative to the fuselage centerline."
    )]
    pub nose_z_m: f64,

    /// Where the nose taper ends and the constant section begins.
    #[config(
        label = "Cabin start X position",
        unit = "m",
        help = "X-station where the fuselage first reaches full diameter, i.e. the end of the nose taper."
    )]
    pub cabin_start_x_m: f64,

    /// Where the constant section sits vertically.
    #[config(
        label = "Cabin vertical offset",
        unit = "m",
        help = "Vertical offset of the cylindrical cabin section relative to the fuselage centerline."
    )]
    pub cabin_z_m: f64,

    /// How much of the length is aft taper.
    #[config(
        label = "Tailcone length",
        unit = "m",
        help = "Length of the aft taper, from the end of the cylindrical cabin section to the tail tip."
    )]
    pub tailcone_length_m: f64,

    /// How far the tail tip rises above the centerline.
    #[config(
        label = "Tail vertical offset",
        unit = "m",
        help = "Vertical offset of the upswept tail tip (positive = tail rises above centerline, typical for ground clearance/rotation)."
    )]
    pub tail_z_m: f64,

    /// Optional user-defined sections inserted into the generated nose/cabin/
    /// tail station list.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    #[config(
        hidden,
        help = "Additional validated fuselage sections supplied by the user; edited by the custom-geometry editor rather than the generated scalar form."
    )]
    pub custom_sections: Vec<FuselageSection>,

    /// Optional per-station overrides for the generated nose/cabin/tail
    /// stations.  The vector is empty until a sandbox user edits a generated
    /// row; once present it contains the complete generated station list in
    /// builder order.  Station X positions remain owned by the body
    /// parameters, while width, height, Z, and shape are independently
    /// editable here.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    #[config(
        hidden,
        help = "Per-station overrides for the generated fuselage loft, written by the sandbox section editor."
    )]
    pub generated_sections: Vec<FuselageSection>,

    /// How many stations the body is lofted through.
    #[config(
        label = "Fuselage cross-section count",
        help = "Number of longitudinal stations used to loft the fuselage body. Higher = smoother surface, slower to draw."
    )]
    pub n_subdivisions: i64,
}

impl Default for FuselageConfig {
    fn default() -> Self {
        // A circular twin-aisle body: a six-metre nose taper, a long
        // constant-section cabin, and a fourteen-metre upswept tailcone.
        Self {
            diameter_m: 6.2,
            height_m: None,
            nose_z_m: -0.5,
            cabin_start_x_m: 6.0,
            cabin_z_m: 0.2,
            tailcone_length_m: 14.0,
            tail_z_m: 1.8,
            custom_sections: Vec::new(),
            generated_sections: Vec::new(),
            n_subdivisions: 12,
        }
    }
}

impl FuselageConfig {
    /// The vertical cross-section dimension, falling back to the diameter.
    ///
    /// An unset height means a circular section, which is the shape the
    /// default describes and the one every consumer has to be able to assume.
    pub fn effective_height_m(&self) -> f64 {
        self.height_m.unwrap_or(self.diameter_m)
    }

    /// Validate user-defined fuselage sections without changing their values.
    pub fn validate_custom_sections(&self) -> Result<(), FuselageSectionError> {
        let mut previous = None;
        for (index, section) in self.custom_sections.iter().enumerate() {
            for (field, value) in [
                ("x_fraction", section.x_fraction),
                ("width_m", section.width_m),
                ("height_m", section.height_m),
                ("z_m", section.z_m),
                ("shape", section.shape),
            ] {
                if !value.is_finite() {
                    return Err(FuselageSectionError::NonFinite {
                        index,
                        field,
                        value,
                    });
                }
            }
            if !(0.0..1.0).contains(&section.x_fraction) {
                return Err(FuselageSectionError::XOutOfRange {
                    index,
                    value: section.x_fraction,
                });
            }
            for (field, value) in [("width", section.width_m), ("height", section.height_m)] {
                if value <= 0.0 {
                    return Err(FuselageSectionError::NonPositive {
                        index,
                        field,
                        value,
                    });
                }
            }
            if !(1.0..=50.0).contains(&section.shape) {
                return Err(FuselageSectionError::InvalidShape {
                    index,
                    value: section.shape,
                });
            }
            if let Some(previous) = previous {
                if section.x_fraction <= previous {
                    return Err(FuselageSectionError::InvalidOrder {
                        index,
                        previous,
                        current: section.x_fraction,
                    });
                }
            }
            previous = Some(section.x_fraction);
        }
        Ok(())
    }

    /// Return custom sections in validated nose-to-tail order.
    pub fn custom_sections_sorted(&self) -> Result<Vec<FuselageSection>, FuselageSectionError> {
        self.validate_custom_sections()?;
        let mut sections = self.custom_sections.clone();
        sections.sort_by(|left, right| left.x_fraction.total_cmp(&right.x_fraction));
        Ok(sections)
    }

    /// Validate the optional generated-station override vector.
    pub fn validate_generated_sections(&self) -> Result<(), FuselageSectionError> {
        const GENERATED_STATION_COUNT: usize = 20;
        if self.generated_sections.is_empty() {
            return Ok(());
        }
        if self.generated_sections.len() != GENERATED_STATION_COUNT {
            return Err(FuselageSectionError::GeneratedSectionCount {
                expected: GENERATED_STATION_COUNT,
                actual: self.generated_sections.len(),
            });
        }
        for (index, section) in self.generated_sections.iter().enumerate() {
            for (field, value) in [
                ("x_fraction", section.x_fraction),
                ("width_m", section.width_m),
                ("height_m", section.height_m),
                ("z_m", section.z_m),
                ("shape", section.shape),
            ] {
                if !value.is_finite() {
                    return Err(FuselageSectionError::NonFinite {
                        index,
                        field,
                        value,
                    });
                }
            }
            if !(0.0..=1.0).contains(&section.x_fraction) {
                return Err(FuselageSectionError::XOutOfRange {
                    index,
                    value: section.x_fraction,
                });
            }
            for (field, value) in [("width", section.width_m), ("height", section.height_m)] {
                if value <= 0.0 {
                    return Err(FuselageSectionError::NonPositive {
                        index,
                        field,
                        value,
                    });
                }
            }
            if !(1.0..=50.0).contains(&section.shape) {
                return Err(FuselageSectionError::InvalidShape {
                    index,
                    value: section.shape,
                });
            }
        }
        Ok(())
    }
}

// A test asserts on values it constructed here directly, so a failed unwrap
// or expect is the assertion failing, not a library invariant being broken.
#[allow(clippy::unwrap_used, clippy::expect_used)]
#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Entry, Kind};

    #[test]
    fn an_unset_height_means_a_circular_section_rather_than_a_flat_one() {
        let fuselage = FuselageConfig::default();
        assert_eq!(fuselage.effective_height_m(), fuselage.diameter_m);
    }

    #[test]
    fn a_declared_height_is_what_an_ovoid_section_is_measured_by() {
        let fuselage = FuselageConfig {
            height_m: Some(7.1),
            ..Default::default()
        };
        assert_eq!(fuselage.effective_height_m(), 7.1);
    }

    #[test]
    fn an_unset_height_reaches_the_form_blank_rather_than_as_zero() {
        // A height box showing 0 would describe a fuselage of no depth, which
        // is a different aircraft from the circular one meant.
        let schema = FuselageConfig::default().schema();
        let Entry::Leaf(leaf) = &schema.field("height_m").unwrap().entry else {
            panic!("the height is not a group");
        };
        assert_eq!(leaf.kind, Kind::Optional);
        assert_eq!(leaf.value, serde_json::Value::Null);
    }

    #[test]
    fn the_nose_droops_and_the_tail_rises() {
        // Tail upsweep is the rotation clearance; a tail below the centerline
        // would strike the runway.
        let fuselage = FuselageConfig::default();
        assert!(fuselage.nose_z_m < 0.0);
        assert!(fuselage.tail_z_m > 0.0);
    }

    #[test]
    fn the_nose_and_the_tailcone_leave_a_cabin_between_them() {
        // The two tapers are measured from opposite ends of a length the
        // design vector owns, so together they have to be shorter than the
        // shortest fuselage the search will accept without penalizing it.
        let fuselage = FuselageConfig::default();
        let tapers = fuselage.cabin_start_x_m + fuselage.tailcone_length_m;
        let floor = crate::ObjectiveWeights::default().fuselage_floor_m;
        assert!(
            tapers < floor,
            "{tapers} m of taper in a {floor} m fuselage"
        );
    }

    #[test]
    fn generated_overrides_require_the_complete_indexed_station_vector() {
        let mut fuselage = FuselageConfig::default();
        fuselage.generated_sections.push(FuselageSection {
            x_fraction: 0.0,
            width_m: 1.0,
            height_m: 1.0,
            z_m: 0.0,
            shape: 2.0,
        });
        assert!(matches!(
            fuselage.validate_generated_sections(),
            Err(FuselageSectionError::GeneratedSectionCount {
                expected: 20,
                actual: 1
            })
        ));
    }
}
