// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Marcos Quiroga Rodriguez

// Ported from alas/config/geometry_config.py (`FuselageConfig`)

//! The fuselage, as the stations its surface is lofted through.
//!
//! Total length is a design variable; what is here is how that length is
//! divided and how the body is shaped along it, where the nose taper ends,
//! how long the tailcone is, and how far the nose and tail tips sit off the
//! centerline. Those three vertical offsets are what give the body its droop
//! and its tail upsweep, which is ground clearance at rotation rather than
//! decoration.
//!
//! Diameter is the one field here that a second discipline reads: the cabin
//! layout takes its usable width from it, so a change made for drag reasons
//! shows up as a seat abreast gained or lost.

use serde::{Deserialize, Serialize};

use crate::ConfigNode;

mod aft_body;
pub use aft_body::AftBodyStation;
mod hump;
mod sections;
pub use hump::{
    BodyStation, UpperDeck, UpperDeckHump, DEFAULT_HUMP_FAIRING_EXPONENT,
    HUMP_FAIRING_EXPONENT_RANGE, HUMP_MAIN_DECK_FLOOR_FRACTION,
};
mod nose;
pub use nose::{NoseShape, NoseStation};

/// An additional user-controlled fuselage section at a normalized X station.
///
/// Width and height are full dimensions in metres. `shape` is the
/// superellipse exponent used by the geometry model; values at or above one
/// keep the cross-section finite and convex for the supported model.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct FuselageSection {
    /// Position along the total fuselage length, strictly inside `(0, 1)`.
    pub x_fraction: f64,
    /// Full local width, in metres.
    pub width_m: f64,
    /// Full local height, in metres.
    pub height_m: f64,
    /// Local centreline vertical offset, in metres.
    pub z_m: f64,
    /// Superellipse exponent used for this section.
    pub shape: f64,
}

/// Why a user-defined fuselage section cannot be lofted safely.
#[derive(Debug, Clone, Copy, PartialEq, thiserror::Error)]
pub enum FuselageSectionError {
    /// The generated-station override list must retain one row for every
    /// generated nose/cabin/tail station so the builder can address rows by
    /// stable station index.
    #[error(
        "generated fuselage section overrides must contain exactly {expected} stations, got {actual}"
    )]
    GeneratedSectionCount {
        /// Number of generated stations emitted by the parametric body.
        expected: usize,
        /// Number of rows supplied by the configuration.
        actual: usize,
    },
    /// A geometric field is not finite.
    #[error("custom fuselage section {index} field {field} must be finite, got {value}")]
    NonFinite {
        /// Zero-based section index.
        index: usize,
        /// Field name.
        field: &'static str,
        /// Invalid value.
        value: f64,
    },
    /// A width or height is zero or negative.
    #[error("custom fuselage section {index} {field} must be positive, got {value}")]
    NonPositive {
        /// Zero-based section index.
        index: usize,
        /// Field name.
        field: &'static str,
        /// Invalid dimension.
        value: f64,
    },
    /// The section is at an endpoint already owned by the generated body.
    #[error("custom fuselage section {index} x fraction must lie strictly in (0, 1), got {value}")]
    XOutOfRange {
        /// Zero-based section index.
        index: usize,
        /// Invalid normalized X station.
        value: f64,
    },
    /// Sections must be supplied nose-to-tail.
    #[error("custom fuselage sections must have strictly increasing x fractions; section {index} has {current} after {previous}")]
    InvalidOrder {
        /// Zero-based section index of the later station.
        index: usize,
        /// Previous normalized X station.
        previous: f64,
        /// Current normalized X station.
        current: f64,
    },
    /// The supported superellipse model does not accept this exponent.
    #[error(
        "custom fuselage section {index} shape must be finite and within [1, 50], got {value}"
    )]
    InvalidShape {
        /// Zero-based section index.
        index: usize,
        /// Invalid exponent.
        value: f64,
    },
    /// The section would share an X station with one generated by the body.
    #[error("custom fuselage section at x fraction {x_fraction} duplicates a generated station")]
    DuplicateGeneratedStation {
        /// Duplicate normalized X station.
        x_fraction: f64,
    },
}

/// Fuselage body-of-revolution or ovoid stations.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ConfigNode)]
#[serde(deny_unknown_fields)]
pub struct FuselageConfig {
    /// The widest cross-section, which sets cabin width and wetted area.
    #[config(
        label = "Fuselage diameter (width)",
        unit = "m",
        help = "Maximum fuselage cross-sectional diameter: the main driver of cabin width and wetted area. Best judged on the 3-view preview's front/isometric panels, not the top view."
    )]
    pub diameter_m: f64,

    /// The vertical dimension, or unset for a circular section.
    #[config(
        label = "Fuselage height (if non-circular)",
        unit = "m",
        help = "Vertical cross-section dimension. Leave blank/none for a circular fuselage where height equals diameter."
    )]
    pub height_m: Option<f64>,

    /// How far the nose tip droops below the centerline.
    #[config(
        label = "Nose vertical offset",
        unit = "m",
        help = "Vertical offset of the nose tip relative to the fuselage centerline."
    )]
    pub nose_z_m: f64,

    /// Where the nose taper ends and the constant section begins.
    #[config(
        label = "Cabin start X position",
        unit = "m",
        help = "X-station where the fuselage first reaches full diameter, i.e. the end of the nose taper."
    )]
    pub cabin_start_x_m: f64,

    /// Where the constant section sits vertically.
    #[config(
        label = "Cabin vertical offset",
        unit = "m",
        help = "Vertical offset of the cylindrical cabin section relative to the fuselage centerline."
    )]
    pub cabin_z_m: f64,

    /// How much of the length is aft taper.
    #[config(
        label = "Tailcone length",
        unit = "m",
        help = "Length of the aft taper, from the end of the cylindrical cabin section to the tail tip."
    )]
    pub tailcone_length_m: f64,

    /// How far the tail tip rises above the centerline.
    #[config(
        label = "Tail vertical offset",
        unit = "m",
        help = "Vertical offset of the upswept tail tip (positive = tail rises above centerline, typical for ground clearance/rotation)."
    )]
    pub tail_z_m: f64,

    /// How far ahead of the tail tip the belly starts to rise; unset or no
    /// longer than the tailcone keeps the tailcone law.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[config(
        label = "Belly upsweep length",
        unit = "m",
        help = "Distance ahead of the tail tip at which the lower fuselage line starts to rise, as a straight line to the tail-tip bottom, while the crown and the width keep the tailcone taper. On a transport the belly rises from near the aft cargo hold, well ahead of the crown taper, and this sets the tail-down (tail-strike) angle at rotation. Leave unset, or no longer than the tailcone, to keep the tailcone law."
    )]
    pub belly_upsweep_length_m: Option<f64>,

    /// Optional shaped-nose parameter; see `nose_shape`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[config(
        label = "Nose windshield angle",
        unit = "deg",
        help = "Side-view angle of the straight windshield to the waterline, between the radome and the crown blend. Setting any nose field replaces the single-ellipsoid nose with upper, lower and plan profiles; fields left unset take narrow-body class estimates (about 32 deg). Valid 15 to 60 deg."
    )]
    pub nose_windshield_angle_deg: Option<f64>,

    /// Optional shaped-nose parameter; see `nose_shape`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[config(
        label = "Nose crown end",
        help = "Fraction of the nose length at which the upper line reaches the cabin crown with zero slope; the windshield blends into the crown there. Unset takes a narrow-body class estimate (about 0.8). Valid 0.55 to 1."
    )]
    pub nose_crown_end_fraction: Option<f64>,

    /// Optional shaped-nose parameter; see `nose_shape`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[config(
        label = "Nose radome length",
        help = "Fraction of the nose length occupied by the radome, from the tip to the windshield base. Unset takes a narrow-body class estimate (about 0.3). Valid 0.1 to 0.45."
    )]
    pub nose_radome_length_fraction: Option<f64>,

    /// Optional shaped-nose parameter; see `nose_shape`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[config(
        label = "Nose keel exponent",
        help = "Exponent of the lower nose line from the tip to the cabin keel: larger values give a deeper chin radome, smaller a straighter underside. Unset takes a narrow-body class estimate (about 2.2). Valid 1.3 to 4."
    )]
    pub nose_keel_exponent: Option<f64>,

    /// Optional shaped-nose parameter; see `nose_shape`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[config(
        label = "Nose plan exponent",
        help = "Exponent of the plan-view half-width from the tip to the cabin width: smaller values give a pointier plan view. Unset takes a narrow-body class estimate (about 2). Valid 1 to 2.6."
    )]
    pub nose_plan_exponent: Option<f64>,

    /// Optional shaped-nose parameter; see `nose_shape`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[config(
        label = "Nose section exponent",
        help = "Peak superellipse exponent of the nose cross-sections, reached mid-nose and returning to 2 (elliptical) at the tip and the cabin; larger values give flatter-sided cockpit sections. Unset takes a narrow-body class estimate (about 2.4). Valid 2 to 3.5."
    )]
    pub nose_section_exponent: Option<f64>,

    /// Optional upper-deck hump; see `hump`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[config(
        label = "Upper-deck hump height",
        unit = "m",
        help = "Rise of the crown above the main crown over the full-height part of an upper-deck hump (Boeing 747 type). Only the crown line rises; the keel, the width and the main deck are unchanged. The hump needs this height and all four hump stations; leave unset for a body without a hump."
    )]
    pub hump_height_m: Option<f64>,

    /// Optional upper-deck hump; see `hump`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[config(
        label = "Hump start station",
        unit = "m",
        help = "Distance from the nose tip at which the crown starts to rise into the hump (the windshield line of a 747)."
    )]
    pub hump_start_x_m: Option<f64>,

    /// Optional upper-deck hump; see `hump`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[config(
        label = "Hump crown start station",
        unit = "m",
        help = "Distance from the nose tip at which the hump reaches its full height; the fore fairing runs from the hump start to here."
    )]
    pub hump_crown_start_x_m: Option<f64>,

    /// Optional upper-deck hump; see `hump`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[config(
        label = "Hump crown end station",
        unit = "m",
        help = "Distance from the nose tip at which the aft fairing of the hump starts to descend."
    )]
    pub hump_crown_end_x_m: Option<f64>,

    /// Optional upper-deck hump; see `hump`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[config(
        label = "Hump end station",
        unit = "m",
        help = "Distance from the nose tip at which the aft fairing of the hump is back on the main crown."
    )]
    pub hump_end_x_m: Option<f64>,

    /// Optional upper-deck hump; see `hump`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[config(
        label = "Hump fairing exponent",
        help = "Exponent of both hump fairings: 2 is tangent to the hump crown with a slope break at the fairing ends, larger values give a fuller hump, 1 a straight ramp. Unset takes 2. Valid 1 to 4."
    )]
    pub hump_fairing_exponent: Option<f64>,

    /// Optional upper deck under the hump; see `hump`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[config(
        label = "Upper-deck floor height",
        unit = "m",
        help = "Height of the upper-deck floor above the main-deck floor under the hump. Setting it makes the hump a passenger deck with its own floor, seats, exits and furnishings; unset leaves the hump as fairing only."
    )]
    pub upper_deck_floor_height_m: Option<f64>,

    /// Optional upper deck under the hump; see `hump`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[config(
        label = "Upper-deck start station",
        unit = "m",
        help = "Distance from the nose tip of the forward end of the usable upper-deck floor (aft of the flight deck). Unset takes the hump crown start."
    )]
    pub upper_deck_start_x_m: Option<f64>,

    /// Optional upper deck under the hump; see `hump`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[config(
        label = "Upper-deck end station",
        unit = "m",
        help = "Distance from the nose tip of the aft end of the usable upper-deck floor. Unset takes the hump crown end."
    )]
    pub upper_deck_end_x_m: Option<f64>,

    /// Optional user-defined sections inserted into the generated nose/cabin/
    /// tail station list.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    #[config(
        hidden,
        help = "Additional validated fuselage sections supplied by the user; edited by the custom-geometry editor rather than the generated scalar form."
    )]
    pub custom_sections: Vec<FuselageSection>,

    /// Optional per-station overrides for the generated nose/cabin/tail
    /// stations.  The vector is empty until a sandbox user edits a generated
    /// row; once present it contains the complete generated station list in
    /// builder order.  Station X positions remain owned by the body
    /// parameters, while width, height, Z, and shape are independently
    /// editable here.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    #[config(
        hidden,
        help = "Per-station overrides for the generated fuselage loft, written by the sandbox section editor."
    )]
    pub generated_sections: Vec<FuselageSection>,

    /// How many stations the body is lofted through.
    #[config(
        label = "Fuselage cross-section count",
        help = "Number of longitudinal stations used to loft the fuselage body. Higher = smoother surface, slower to draw."
    )]
    pub n_subdivisions: i64,
}

impl Default for FuselageConfig {
    fn default() -> Self {
        // A circular twin-aisle body: a six-metre nose taper, a long
        // constant-section cabin, and a fourteen-metre upswept tailcone.
        Self {
            diameter_m: 6.2,
            height_m: None,
            nose_z_m: -0.5,
            cabin_start_x_m: 6.0,
            cabin_z_m: 0.2,
            tailcone_length_m: 14.0,
            tail_z_m: 1.8,
            belly_upsweep_length_m: None,
            nose_windshield_angle_deg: None,
            nose_crown_end_fraction: None,
            nose_radome_length_fraction: None,
            nose_keel_exponent: None,
            nose_plan_exponent: None,
            nose_section_exponent: None,
            hump_height_m: None,
            hump_start_x_m: None,
            hump_crown_start_x_m: None,
            hump_crown_end_x_m: None,
            hump_end_x_m: None,
            hump_fairing_exponent: None,
            upper_deck_floor_height_m: None,
            upper_deck_start_x_m: None,
            upper_deck_end_x_m: None,
            custom_sections: Vec::new(),
            generated_sections: Vec::new(),
            n_subdivisions: 12,
        }
    }
}

impl FuselageConfig {
    /// The vertical cross-section dimension, falling back to the diameter.
    ///
    /// An unset height means a circular section, which is the shape the
    /// default describes and the one every consumer has to be able to assume.
    pub fn effective_height_m(&self) -> f64 {
        self.height_m.unwrap_or(self.diameter_m)
    }
}

// A test asserts on values it constructed here directly, so a failed unwrap
// or expect is the assertion failing, not a library invariant being broken.
#[allow(clippy::unwrap_used, clippy::expect_used)]
#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Entry, Kind};

    #[test]
    fn an_unset_height_means_a_circular_section_rather_than_a_flat_one() {
        let fuselage = FuselageConfig::default();
        assert_eq!(fuselage.effective_height_m(), fuselage.diameter_m);
    }

    #[test]
    fn a_declared_height_is_what_an_ovoid_section_is_measured_by() {
        let fuselage = FuselageConfig {
            height_m: Some(7.1),
            ..Default::default()
        };
        assert_eq!(fuselage.effective_height_m(), 7.1);
    }

    #[test]
    fn an_unset_height_reaches_the_form_blank_rather_than_as_zero() {
        // A height box showing 0 would describe a fuselage of no depth, which
        // is a different aircraft from the circular one meant.
        let schema = FuselageConfig::default().schema();
        let Entry::Leaf(leaf) = &schema.field("height_m").unwrap().entry else {
            panic!("the height is not a group");
        };
        assert_eq!(leaf.kind, Kind::Optional);
        assert_eq!(leaf.value, serde_json::Value::Null);
    }

    #[test]
    fn the_nose_droops_and_the_tail_rises() {
        // Tail upsweep is the rotation clearance; a tail below the centerline
        // would strike the runway.
        let fuselage = FuselageConfig::default();
        assert!(fuselage.nose_z_m < 0.0);
        assert!(fuselage.tail_z_m > 0.0);
    }

    #[test]
    fn the_nose_and_the_tailcone_leave_a_cabin_between_them() {
        // The two tapers are measured from opposite ends of a length the
        // design vector owns, so together they have to be shorter than the
        // shortest fuselage the search will accept.
        let fuselage = FuselageConfig::default();
        let tapers = fuselage.cabin_start_x_m + fuselage.tailcone_length_m;
        let floor = crate::DESIGN_VARIABLE_SPECS
            .iter()
            .find(|spec| spec.name == "fuselage_length_m")
            .map(|spec| spec.lower)
            .unwrap();
        assert!(
            tapers < floor,
            "{tapers} m of taper in a {floor} m fuselage"
        );
    }

    #[test]
    fn generated_overrides_require_the_complete_indexed_station_vector() {
        let mut fuselage = FuselageConfig::default();
        fuselage.generated_sections.push(FuselageSection {
            x_fraction: 0.0,
            width_m: 1.0,
            height_m: 1.0,
            z_m: 0.0,
            shape: 2.0,
        });
        assert!(matches!(
            fuselage.validate_generated_sections(),
            Err(FuselageSectionError::GeneratedSectionCount {
                expected: 20,
                actual: 1
            })
        ));
    }
}
