// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Marcos Quiroga Rodriguez

//! The eight OEW reference records, one per registered preset.
//!
//! Every value here was read from the retained document named in its
//! source; the quote is the wording on the page. A value whose document is
//! not retained is labelled by tier and never promoted.

use super::sources::{
    unknown, A220_ACP, A220_ARP, A320_ACAP_REV46, A320_F_HDRF_SHEET, A340_ACAP_REV33,
    A380_ACAP_REV20, A380_AGGREGATOR, ATR_FACTSHEET, B777X_ACAP_REV_G, B787_ACAP_REV_L, DC10_ACAP,
    DC10_ACAP_30CF, RETRIEVED,
};
use super::{
    InclusionStatus, OewApplicability, OewCaseAnchor, OewInclusionList, OewReference,
    OewReferenceConfiguration, OewSource, OewSourceTier, PublishedOewValue,
};

pub(super) static RECORDS: &[OewReference] = &[
    OewReference {
        preset: "AVE",
        applicability: OewApplicability::NotApplicable,
        reference_oew_kg: None,
        definition_label: "none: notional design",
        reference_configuration: OewReferenceConfiguration {
            model: "AVE-v1",
            weight_variant: "notional design requirement",
            mtow_kg: Some(358_670.0),
            engine: "GE9X family conceptual installation",
            modification_state: "AVE-v1 design baseline",
            cabin: "auto-sized product cabin",
        },
        differences_from_preset: &[],
        inclusion: unknown(),
        source: None,
        uncertainty_kg: None,
        case_anchor: None,
        other_published_values: &[PublishedOewValue {
            label: "Boeing 777-9 planning benchmark: no numeric OEW published",
            value_kg: 0.0,
            is_operating_empty: false,
            source: B777X_ACAP_REV_G,
            note: "the 777-9 is a benchmark for AVE's geometry class, not a measurement of AVE",
        }],
        structural_payload_basis_oew_kg: None,
        notes: "AVE is notional; no aircraft OEW exists and none may be inferred from the 777-9.",
    },
    OewReference {
        preset: "A340-300",
        applicability: OewApplicability::ConditionalMismatch,
        reference_oew_kg: Some(131_215.0),
        definition_label: "OEW printed on the jacking-dimensions figure (aircraft on wheels with standard tires)",
        reference_configuration: OewReferenceConfiguration {
            model: "A340-300",
            weight_variant: "not stated on the figure",
            mtow_kg: None,
            engine: "not stated (CFM56-5C family)",
            modification_state: "not stated",
            cabin: "not stated; the document's typical layout is 335 seats (30 first, 305 tourist)",
        },
        differences_from_preset: &[
            "weight variant WV029 is not identified on the figure",
            "cabin and equipment configuration are not stated; the preset seats 375Y in the product cabin",
            "the printed 279 279 lb does not convert from 131 215 kg (= 289 278 lb); the kilogram value is retained",
        ],
        inclusion: unknown(),
        source: Some(A340_ACAP_REV33),
        uncertainty_kg: Some(2_000.0),
        case_anchor: None,
        other_published_values: &[
            PublishedOewValue {
                label: "A340-200 jacking-dimensions figure OEW",
                value_kg: 127_000.0,
                is_operating_empty: true,
                source: OewSource {
                    locator: "2-14-0 page 8, Figure 2-14-0-991-012-A01 (PDF page 142)",
                    quote: "AIRCRAFT ON WHEELS WITH STANDARD TIRES, OEW 127 000 kg (279 987 lb)",
                    ..A340_ACAP_REV33
                },
                note: "different model; shown because its pound value converts correctly and supports the kilogram reading of the -300 figure",
            },
            PublishedOewValue {
                label: "empty weight for maintenance (depending on the aircraft configuration)",
                value_kg: 125_000.0,
                is_operating_empty: false,
                source: OewSource {
                    locator: "2-3-0 Ground Clearances, Figure 2-3-0-991-005-A01 (PDF page 44)",
                    quote: "125 000 kg (275 578 lb) ... EMPTY WEIGHT FOR MAINTENANCE (DEPENDING ON THE AIRCRAFT CONFIGURATION)",
                    ..A340_ACAP_REV33
                },
                note: "a maintenance configuration weight, not an operating empty weight",
            },
        ],
        structural_payload_basis_oew_kg: None,
        notes: "Primary Airbus figure labelled OEW but not tied to WV029 or to a cabin; comparable only as a typical-configuration anchor with a stated uncertainty. The declared structural payload 48,600 kg is an upstream value with no documented OEW derivation.",
    },
    OewReference {
        preset: "A380-800",
        applicability: OewApplicability::SourceGap,
        reference_oew_kg: None,
        definition_label: "none in Airbus ACAP Rev 20, Facts and Figures 2022 or EASA TCDS A.110",
        reference_configuration: OewReferenceConfiguration {
            model: "A380-841",
            weight_variant: "WV000",
            mtow_kg: Some(560_000.0),
            engine: "Trent 970-84",
            modification_state: "WV000 public planning baseline",
            cabin: "product cabin 98 business / 565 economy (663 seats)",
        },
        differences_from_preset: &[],
        inclusion: unknown(),
        source: None,
        uncertainty_kg: None,
        case_anchor: Some(OewCaseAnchor {
            case_label: "A380_typical_555_three_class_declared",
            value_kg: 277_000.0,
            configuration: OewReferenceConfiguration {
                model: "A380-800",
                weight_variant: "not stated",
                mtow_kg: None,
                engine: "not stated",
                modification_state: "not stated",
                cabin: "typical three-class cabin of about 500-555 seats",
            },
            source: A380_AGGREGATOR,
            uncertainty_kg: Some(8_000.0),
            residual_mismatch: &[
                "no primary document; consulted values span 270.1 t to 285 t",
                "cabin, crew and equipment definition unknown",
            ],
        }),
        other_published_values: &[PublishedOewValue {
            label: "maximum jacking weight",
            value_kg: 333_700.0,
            is_operating_empty: false,
            source: A380_ACAP_REV20,
            note: "a jacking limit, not an empty weight",
        }],
        structural_payload_basis_oew_kg: Some(277_000.0),
        notes: "The 277,000 kg figure is an aggregator value; it is visible against the declared typical three-class case and excluded from every metric.",
    },
    OewReference {
        preset: "B787-9",
        applicability: OewApplicability::SourceGap,
        reference_oew_kg: None,
        definition_label: "none in Boeing ACAP D6-58333 Rev Q (current) or Rev P",
        reference_configuration: OewReferenceConfiguration {
            model: "787-9",
            weight_variant: "legacy 561,500 lb MTOW",
            mtow_kg: Some(254_692.0),
            engine: "GEnx-1B74/75 P2 family",
            modification_state: "Boeing Rev Q legacy-weight planning baseline",
            cabin: "product cabin 42 business / 260 economy (302 seats)",
        },
        differences_from_preset: &[],
        inclusion: unknown(),
        source: None,
        uncertainty_kg: None,
        case_anchor: Some(OewCaseAnchor {
            case_label: "B787_typical_two_class_290_declared",
            value_kg: 128_850.0,
            configuration: OewReferenceConfiguration {
                model: "787-9",
                weight_variant: "not stated in the retained attribution",
                mtow_kg: None,
                engine: "not stated",
                modification_state: "2015 planning standard",
                cabin: "typical two-class 290 seats (28 business, 262 tourist)",
            },
            source: B787_ACAP_REV_L,
            uncertainty_kg: Some(3_000.0),
            residual_mismatch: &[
                "the superseded Rev L page is not retained; the attribution could not be verified",
                "inclusion list and installed equipment unknown",
            ],
        }),
        other_published_values: &[],
        structural_payload_basis_oew_kg: Some(128_850.0),
        notes: "Rev Q defines OEW (page 17) but prints no value. The 128,850 kg figure stays a conditional anchor against the declared 28C/262Y case until the Rev L page is retrieved.",
    },
    OewReference {
        preset: "A320-200",
        applicability: OewApplicability::SourceGap,
        reference_oew_kg: None,
        definition_label: "none for A320-214 WV017 with Sharklets in the retained primary documents",
        reference_configuration: OewReferenceConfiguration {
            model: "A320-214",
            weight_variant: "WV017 (78,000 kg MTOW)",
            mtow_kg: Some(78_000.0),
            engine: "CFM56-5B4/3",
            modification_state: "MOD160500 Sharklets; MOD37147 Tech Insertion",
            cabin: "product cabin 180Y (exit-limited)",
        },
        differences_from_preset: &[],
        inclusion: unknown(),
        source: None,
        uncertainty_kg: None,
        case_anchor: Some(OewCaseAnchor {
            case_label: "A320_F-HDRF_77t_180Y",
            value_kg: 41_052.0,
            configuration: OewReferenceConfiguration {
                model: "A320-214",
                weight_variant: "77,000 kg MTOW (MLW 64,500 kg, MZFW 61,000 kg)",
                mtow_kg: Some(77_000.0),
                engine: "CFM56-5B4/3",
                modification_state: "wingtip fences (no Sharklets)",
                cabin: "180 seats, single class",
            },
            source: A320_F_HDRF_SHEET,
            uncertainty_kg: Some(1_500.0),
            residual_mismatch: &[
                "inclusion list of the 41,052 kg empty weight not stated",
                "wingtip-fence span 34.10 m not applied to the geometry (wing sensitivity -455 kg recorded)",
                "operator interior, catering and equipment unknown",
            ],
        }),
        other_published_values: &[
            PublishedOewValue {
                label: "empty weight for maintenance",
                value_kg: 45_000.0,
                is_operating_empty: false,
                source: OewSource {
                    locator: "2-3-0 Ground Clearances figures (A320-200 with wingtip fences and with Sharklets)",
                    quote: "45 000 kg (99 208 lb) EMPTY WEIGHT FOR MAINTENANCE",
                    ..A320_ACAP_REV46
                },
                note: "a maintenance configuration weight, not an operating empty weight",
            },
            PublishedOewValue {
                label: "aircraft configuration for rescue and fire-fighting clearances",
                value_kg: 41_000.0,
                is_operating_empty: false,
                source: OewSource {
                    locator: "10-0-0 Aircraft Rescue and Fire Fighting, page 15, Figure 10-0-0-991-041-A01",
                    quote: "41 000 kg (90 389 lb) AFT CG (26.5%) A/C CONFIGURATION",
                    ..A320_ACAP_REV46
                },
                note: "a clearance-drawing configuration shared with the A320neo; not labelled as an empty weight",
            },
            PublishedOewValue {
                label: "preset legacy value attributed to an Airbus ground-clearance table",
                value_kg: 41_244.0,
                is_operating_empty: false,
                source: OewSource {
                    document: "ALAS preset registry",
                    publisher: "ALAS",
                    revision: "working tree",
                    date: "2026-09-11",
                    locator: "A320-200.reference.oew_kg (history)",
                    url: "",
                    local_path: "crates/alas-config/src/presets/narrowbody.rs (history)",
                    retrieved: RETRIEVED,
                    quote: "41,244 kg; absent from ACAP Revision 46 (2026-07-01)",
                    tier: OewSourceTier::PresetLegacyValue,
                },
                note: "not present in the cited current document; retained only as the basis of the declared structural payload",
            },
        ],
        structural_payload_basis_oew_kg: Some(41_244.0),
        notes: "The registered aircraft has no configuration-matched OEW. The 41,052 kg sheet is compared only through the reconstructed 77 t / 180Y / fence-tip case.",
    },
    OewReference {
        preset: "A220-300",
        applicability: OewApplicability::ConditionalMismatch,
        reference_oew_kg: Some(37_149.0),
        definition_label: "OEW, Airbus A220 Aircraft Recovery Publication design-weights table (planning value where an actual OEW is unavailable)",
        reference_configuration: OewReferenceConfiguration {
            model: "BD-500-1A11 (A220-300)",
            weight_variant: "149,000 lb MTOW (67,585 kg)",
            mtow_kg: Some(67_585.0),
            engine: "PW1521G-3",
            modification_state: "S/N 55001-59999 planning configuration",
            cabin: "standard 140-seat planning cabin",
        },
        differences_from_preset: &[
            "the product cabin seats 145Y (exit-limited); the planning cabin is 140Y",
            "operator interior and installed equipment not stated",
        ],
        inclusion: OewInclusionList {
            flight_crew: InclusionStatus::Included,
            cabin_crew: InclusionStatus::Included,
            crew_baggage: InclusionStatus::Included,
            unusable_fuel: InclusionStatus::Included,
            engine_oil: InclusionStatus::Included,
            galley_equipment_and_catering: InclusionStatus::Included,
            potable_water: InclusionStatus::Included,
            seats_and_furnishings: InclusionStatus::Included,
            cargo_containers: InclusionStatus::Unknown,
            manuals_and_operational_items: InclusionStatus::Included,
            usable_fuel: InclusionStatus::Excluded,
            payload: InclusionStatus::Excluded,
        },
        source: Some(A220_ARP),
        uncertainty_kg: Some(500.0),
        case_anchor: None,
        other_published_values: &[PublishedOewValue {
            label: "Operating Weight Empty (OWE), standard seating capacity 140",
            value_kg: 37_081.0,
            is_operating_empty: true,
            source: A220_ACP,
            note: "same manufacturer, same weight variant; 68 kg below the recovery-publication planning OEW",
        }],
        structural_payload_basis_oew_kg: Some(37_149.0),
        notes: "Primary Airbus planning value with a stated inclusion list; the remaining mismatch is the cabin count and the unknown operator fit. The holdout anchor is unchanged.",
    },
    OewReference {
        preset: "ATR72-600",
        applicability: OewApplicability::UnsupportedModel,
        reference_oew_kg: Some(13_450.0),
        definition_label: "typical in-service operational empty weight",
        reference_configuration: OewReferenceConfiguration {
            model: "ATR 72-212A (ATR 72-600)",
            weight_variant: "23,000 kg MTOW",
            mtow_kg: Some(23_000.0),
            engine: "PW127M",
            modification_state: "ATR 72-600 commercial standard",
            cabin: "72-seat factsheet reference",
        },
        differences_from_preset: &["the pure FLOPS transport model has no propeller or shaft-power branch; no prediction exists to compare with"],
        inclusion: unknown(),
        source: Some(ATR_FACTSHEET),
        uncertainty_kg: Some(440.0),
        case_anchor: None,
        other_published_values: &[PublishedOewValue {
            label: "technical-specification OEW basis",
            value_kg: 13_010.0,
            is_operating_empty: true,
            source: OewSource {
                revision: "ATR technical specification basis (2012 datasheet gives 13,311 kg)",
                quote: "28,682 lb (13,010 kg)",
                ..ATR_FACTSHEET
            },
            note: "the 440 kg spread between the factsheet bases is the standard-equipment / in-service allowance",
        }],
        structural_payload_basis_oew_kg: Some(13_450.0),
        notes: "Manufacturer record retained for the aircraft; the model is unsupported, so the record is excluded from every metric.",
    },
    OewReference {
        preset: "DC-10",
        applicability: OewApplicability::ConditionalMismatch,
        reference_oew_kg: Some(120_914.0),
        definition_label: "Operating Weight Empty, ACAP Series 30 passenger column adjusted by the 572,000-pound MTOGW footnote (266,191 + 379 = 266,570 lb)",
        reference_configuration: OewReferenceConfiguration {
            model: "DC-10-30 passenger",
            weight_variant: "572,000 lb MTOGW option (259,454 kg); landing weight 421,000 lb (190,962 kg); MZFW 368,000 lb (166,922 kg)",
            mtow_kg: Some(259_454.0),
            engine: "CF6-50C",
            modification_state: "ACAP Revision A planning standard (2004)",
            cabin: "ACAP standard seating 255 (class split not published)",
        },
        differences_from_preset: &[
            "the product cabin seats 243 (36 business, 207 economy) against the ACAP standard 255",
            "the ACAP OWE is a typical configuration figure; installed equipment and operator items are not itemized",
        ],
        inclusion: OewInclusionList {
            flight_crew: InclusionStatus::Included,
            cabin_crew: InclusionStatus::Included,
            crew_baggage: InclusionStatus::Unknown,
            unusable_fuel: InclusionStatus::Included,
            engine_oil: InclusionStatus::Unknown,
            galley_equipment_and_catering: InclusionStatus::Included,
            potable_water: InclusionStatus::Unknown,
            seats_and_furnishings: InclusionStatus::Included,
            cargo_containers: InclusionStatus::Unknown,
            manuals_and_operational_items: InclusionStatus::Included,
            usable_fuel: InclusionStatus::Excluded,
            payload: InclusionStatus::Excluded,
        },
        source: Some(DC10_ACAP),
        uncertainty_kg: Some(2_000.0),
        case_anchor: Some(OewCaseAnchor {
            case_label: "DC10_standard_555k_row_declared",
            value_kg: 120_742.0,
            configuration: OewReferenceConfiguration {
                model: "DC-10-30 passenger",
                weight_variant: "standard 555,000 lb row: MTOW 251,744 kg, MLW 182,798 kg, MZFW 166,922 kg",
                mtow_kg: Some(251_744.0),
                engine: "CF6-50C",
                modification_state: "ACAP Revision A planning standard (2004)",
                cabin: "ACAP standard seating 255 (class split not published)",
            },
            source: DC10_ACAP,
            uncertainty_kg: Some(2_000.0),
            residual_mismatch: &["same document and cabin as the comparable value; only the weight option differs"],
        }),
        other_published_values: &[PublishedOewValue {
            label: "Series 30CF passenger-mode Operating Weight Empty",
            value_kg: 121_904.0,
            is_operating_empty: true,
            source: DC10_ACAP_30CF,
            note: "convertible-freighter airframe in passenger mode (MLW 186,427 kg, MZFW 177,355 kg); a different model column that earlier audits mislabelled as the standard passenger row",
        }],
        structural_payload_basis_oew_kg: Some(120_914.0),
        notes: "The ACAP defines OWE as structure, power plant, furnishing, systems, unusable fuel and other unusable propulsion agents, standard items, personnel, equipment and supplies necessary for full operation, excluding fuel and payload. The preset's 120,914 kg, 190,962 kg landing weight and 46,008 kg structural payload are exactly the passenger column with the 572,000 lb footnote applied.",
    },
];
