// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Marcos Quiroga Rodriguez

//! Preliminary fixed-wing geometry and structural-mass relations.

use std::f64::consts::PI;

use crate::catalog::Dimensions;
use crate::feasibility::{EquipmentBay, Placement};
use crate::{Finding, FindingKind, Severity};

use super::{CandidateSample, PreliminaryModel};

/// Generated constant-chord preliminary wing geometry.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct WingGeometry {
    /// Reference area.
    pub area_m2: f64,
    /// Aspect ratio.
    pub aspect_ratio: f64,
    /// Span.
    pub span_m: f64,
    /// Mean chord.
    pub mean_chord_m: f64,
    /// Leading-edge body-axis x location.
    pub leading_edge_x_m: f64,
}

/// Generated fuselage and usable internal equipment-bay geometry.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct FuselageGeometry {
    /// Overall length.
    pub length_m: f64,
    /// Outer diameter of the preliminary circular envelope.
    pub diameter_m: f64,
    /// Usable rectangular internal bay.
    pub equipment_bay: EquipmentBay,
}

/// Tail geometry generated from horizontal and vertical volume coefficients.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EmpennageGeometry {
    /// Horizontal-tail reference area.
    pub horizontal_area_m2: f64,
    /// Horizontal-tail span.
    pub horizontal_span_m: f64,
    /// Vertical-tail reference area.
    pub vertical_area_m2: f64,
    /// Vertical-tail height represented by its aspect-ratio span.
    pub vertical_span_m: f64,
    /// Quarter-chord distance from wing to tail.
    pub tail_arm_m: f64,
}

/// Landing-gear layout and propeller-clearance sizing inputs.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LandingGearGeometry {
    /// Main-wheel lateral track.
    pub track_m: f64,
    /// Longitudinal nose-to-main wheelbase.
    pub wheelbase_m: f64,
    /// Minimum leg length implied by propeller radius and clearance.
    pub minimum_leg_length_m: f64,
    /// Positive design load factor passed to detailed gear sizing.
    pub design_load_factor: f64,
}

/// Complete preliminary outer geometry generated by the optimizer.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct GeneratedGeometry {
    /// Main wing.
    pub wing: WingGeometry,
    /// Fuselage and equipment bay.
    pub fuselage: FuselageGeometry,
    /// Horizontal and vertical tails.
    pub empennage: EmpennageGeometry,
    /// Landing-gear sizing inputs.
    pub landing_gear: LandingGearGeometry,
}

#[derive(Clone, Copy)]
pub(super) struct MassElement {
    pub(super) mass_kg: f64,
    pub(super) x_m: f64,
}

pub(super) fn wing_geometry(sample: CandidateSample) -> WingGeometry {
    let span_m = (sample.wing_area_m2 * sample.wing_aspect_ratio).sqrt();
    WingGeometry {
        area_m2: sample.wing_area_m2,
        aspect_ratio: sample.wing_aspect_ratio,
        span_m,
        mean_chord_m: sample.wing_area_m2 / span_m,
        leading_edge_x_m: sample.wing_leading_edge_fraction * sample.fuselage_length_m,
    }
}

pub(super) fn empennage_geometry(
    wing: WingGeometry,
    tail_arm_m: f64,
    model: PreliminaryModel,
) -> EmpennageGeometry {
    // Raymer's tail-volume definitions preserve the relevant wing scale and
    // tail moment arm instead of assigning an arbitrary tail-area fraction.
    let horizontal_area_m2 =
        model.horizontal_tail_volume_coefficient * wing.area_m2 * wing.mean_chord_m / tail_arm_m;
    let vertical_area_m2 =
        model.vertical_tail_volume_coefficient * wing.area_m2 * wing.span_m / tail_arm_m;
    EmpennageGeometry {
        horizontal_area_m2,
        horizontal_span_m: (horizontal_area_m2 * model.horizontal_tail_aspect_ratio).sqrt(),
        vertical_area_m2,
        vertical_span_m: (vertical_area_m2 * model.vertical_tail_aspect_ratio).sqrt(),
        tail_arm_m,
    }
}

pub(super) fn fuselage_geometry(
    length_m: f64,
    equipment: [Dimensions; 6],
    skin_thickness_m: f64,
    model: PreliminaryModel,
) -> Result<FuselageGeometry, Vec<Finding>> {
    let internal_width_m = equipment
        .iter()
        .map(|item| item.width_m)
        .fold(0.0_f64, f64::max)
        + 2.0 * model.equipment_clearance_m;
    let internal_height_m = equipment
        .iter()
        .map(|item| item.height_m)
        .fold(0.0_f64, f64::max)
        + 2.0 * model.equipment_clearance_m;
    let bay = EquipmentBay {
        min_x_m: model.nose_length_fraction * length_m,
        max_x_m: (1.0 - model.tailcone_length_fraction) * length_m,
        min_y_m: -0.5 * internal_width_m,
        max_y_m: 0.5 * internal_width_m,
        min_z_m: -0.5 * internal_height_m,
        max_z_m: 0.5 * internal_height_m,
    };
    let required_length_m = equipment.iter().map(|item| item.length_m).sum::<f64>()
        + (equipment.len() + 1) as f64 * model.equipment_gap_m;
    let available_length_m = bay.max_x_m - bay.min_x_m;
    if required_length_m > available_length_m {
        return Err(vec![Finding {
            severity: Severity::Failure,
            kind: FindingKind::PackagingViolation,
            subject: "equipment bay".to_owned(),
            message: "sequential component envelopes exceed usable fuselage length".to_owned(),
            required: Some(required_length_m),
            available: Some(available_length_m),
            units: Some("m"),
        }]);
    }
    Ok(FuselageGeometry {
        length_m,
        diameter_m: internal_width_m.hypot(internal_height_m) + 2.0 * skin_thickness_m,
        equipment_bay: bay,
    })
}

pub(super) fn airframe_masses(
    geometry: GeneratedGeometry,
    density_kg_m3: f64,
    thickness_m: f64,
    landing_gear_mass_kg: f64,
    model: PreliminaryModel,
) -> [MassElement; 6] {
    let wing = geometry.wing;
    let cap_width_m = model.spar_cap_width_fraction * wing.mean_chord_m;
    [
        MassElement {
            mass_kg: 2.0 * wing.area_m2 * thickness_m * density_kg_m3,
            x_m: wing.leading_edge_x_m + 0.5 * wing.mean_chord_m,
        },
        MassElement {
            mass_kg: 2.0 * wing.span_m * cap_width_m * thickness_m * density_kg_m3,
            x_m: wing.leading_edge_x_m + 0.3 * wing.mean_chord_m,
        },
        MassElement {
            mass_kg: PI
                * geometry.fuselage.diameter_m
                * geometry.fuselage.length_m
                * thickness_m
                * density_kg_m3,
            x_m: 0.5 * geometry.fuselage.length_m,
        },
        MassElement {
            mass_kg: 2.0
                * (geometry.empennage.horizontal_area_m2 + geometry.empennage.vertical_area_m2)
                * thickness_m
                * density_kg_m3,
            x_m: 0.9 * geometry.fuselage.length_m,
        },
        MassElement {
            mass_kg: landing_gear_mass_kg,
            x_m: wing.leading_edge_x_m + 0.25 * wing.mean_chord_m,
        },
        MassElement {
            mass_kg: model.fixed_systems_mass_kg,
            x_m: 0.5 * geometry.fuselage.length_m,
        },
    ]
}

pub(super) fn place_equipment(
    bay: EquipmentBay,
    dimensions: [Dimensions; 6],
    gap_m: f64,
) -> [Placement; 6] {
    let mut cursor = bay.min_x_m + gap_m;
    dimensions.map(|item| {
        let placement = Placement {
            center_x_m: cursor + 0.5 * item.length_m,
            center_y_m: 0.0,
            center_z_m: 0.0,
            inside_equipment_bay: true,
        };
        cursor += item.length_m + gap_m;
        placement
    })
}
