// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSidecarError():Promise<string>;

export function GetSidecarPort():Promise<number>;

export function LogFrontendEvent(arg1:string,arg2:string):Promise<void>;

export function ReportBridgeCheckResult(arg1:boolean,arg2:string):Promise<void>;

export function RetrySidecar():Promise<void>;
