// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSidecarError() {
  return window['go']['main']['App']['GetSidecarError']();
}

export function GetSidecarPort() {
  return window['go']['main']['App']['GetSidecarPort']();
}

export function LogFrontendEvent(arg1, arg2) {
  return window['go']['main']['App']['LogFrontendEvent'](arg1, arg2);
}

export function ReportBridgeCheckResult(arg1, arg2) {
  return window['go']['main']['App']['ReportBridgeCheckResult'](arg1, arg2);
}

export function RetrySidecar() {
  return window['go']['main']['App']['RetrySidecar']();
}
