// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Marcos Quiroga Rodriguez

//! Rendering the AngelScript source.

use super::*;

pub(super) fn render_script(
    airplane: &Airplane,
    landing_gear: Option<&LandingGearLayout>,
    vsp3_name: &str,
    cad_preview_vsp3_name: &str,
    preview_name: &str,
) -> String {
    let mut script = String::new();
    script.push_str("// Generated by ALAS from computed geometry.\n");
    script.push_str(
        "// OpenVSP API reference: AddGeom, SetParmVal, SetAirfoilPnts, WriteVSPFile.\n\n",
    );
    script.push_str("int main()\n{\n    ClearVSPModel();\n\n");

    for (index, fuselage) in airplane.fuselages.iter().enumerate() {
        emit_fuselage(&mut script, index, fuselage);
    }
    for (index, wing) in airplane.wings.iter().enumerate() {
        emit_wing(&mut script, index, wing);
    }
    if let Some(gear) = landing_gear {
        emit_landing_gear(&mut script, airplane, gear);
    }

    script.push_str(
        "    Update();\n\
         // Keep the native CAD preview as a best-effort artifact.  The\n\
         // model/error contract below remains authoritative for runtime\n\
         // acceptance, so a graphics-context limitation cannot turn a valid\n\
         // VSP3 export into a false solver failure.\n\
         FitAllViews();\n\
         SetViewAxis( false );\n\
         SetShowBorders( false );\n",
    );
    let _ = writeln!(
        script,
        "    WriteVSPFile(\"{}\", SET_ALL);",
        script_string(vsp3_name)
    );
    script.push_str(
        "    string alas_vspaero_geometry_analysis = \"VSPAEROComputeGeometry\";\n\
         \x20   SetAnalysisInputDefaults( alas_vspaero_geometry_analysis );\n\
         \x20   SetIntAnalysisInput( alas_vspaero_geometry_analysis, \"GeomSet\", { SET_NONE }, 0 );\n\
         \x20   SetIntAnalysisInput( alas_vspaero_geometry_analysis, \"ThinGeomSet\", { 3 }, 0 );\n\
         \x20   string alas_vspaero_geometry_result = ExecAnalysis( alas_vspaero_geometry_analysis );\n\
         \x20   if ( alas_vspaero_geometry_result.length() > 0 )\n\
         \x20   {\n\
         \x20       Print( string( \"ALAS_VSPAERO_GEOMETRY_COMPLETE\\n\" ) );\n\
         \x20   }\n",
    );
    script.push_str(
        "    int alas_model_error_count = GetNumTotalErrors();\n\
         \x20   while ( GetNumTotalErrors() > 0 )\n\
         \x20   {\n\
         \x20       ErrorObj err = PopLastError();\n\
         \x20       Print( err.GetErrorString() );\n\
         \x20   }\n\
         \x20   if ( alas_model_error_count == 0 )\n\
         \x20   {\n",
    );
    script.push_str(
        "         \x20   // The thin-surface mesh above is exactly what the native\n\
         \x20   // VSPAERO solver reads and is never modified for display\n\
         \x20   // purposes. This second, independent export adds the fuselage\n\
         \x20   // and landing-gear bodies as thick VSPAERO panels so the\n\
         \x20   // report/GUI CAD preview can show the whole outer mold line.\n\
         \x20   // A failure here is cosmetic and must not affect the solver\n\
         \x20   // export accepted above.\n",
    );
    let _ = writeln!(
        script,
        "    \x20   WriteVSPFile(\"{}\", SET_ALL);",
        script_string(cad_preview_vsp3_name)
    );
    script.push_str(
        "    \x20   string alas_cad_preview_geometry_analysis = \"VSPAEROComputeGeometry\";\n\
         \x20       SetAnalysisInputDefaults( alas_cad_preview_geometry_analysis );\n\
         \x20       SetIntAnalysisInput( alas_cad_preview_geometry_analysis, \"GeomSet\", { 4 }, 0 );\n\
         \x20       SetIntAnalysisInput( alas_cad_preview_geometry_analysis, \"ThinGeomSet\", { 3 }, 0 );\n\
         \x20       string alas_cad_preview_geometry_result = ExecAnalysis( alas_cad_preview_geometry_analysis );\n\
         \x20       if ( alas_cad_preview_geometry_result.length() > 0 )\n\
         \x20       {\n\
         \x20           Print( string( \"ALAS_OPENVSP_CAD_PREVIEW_GEOMETRY_COMPLETE\\n\" ) );\n\
         \x20       }\n\
         \x20       while ( GetNumTotalErrors() > 0 )\n\
         \x20       {\n\
         \x20           ErrorObj preview_geometry_error = PopLastError();\n\
         \x20           Print( string( \"ALAS_OPENVSP_CAD_PREVIEW_WARNING: \" ) + preview_geometry_error.GetErrorString() );\n\
         \x20       }\n\
         \x20       // ScreenGrab requires OpenVSP's GUI build and an available\n\
         \x20       // graphics context. Keep that optional artifact separate\n\
         \x20       // from model validity so headless export stays truthful.\n\
         \x20       if ( IsGUIBuild() )\n\
         \x20       {\n",
    );
    let _ = writeln!(
        script,
        "         \x20       ScreenGrab(\"{}\", 1600, 900, true, true);",
        script_string(preview_name)
    );
    script.push_str(
        "         \x20       while ( GetNumTotalErrors() > 0 )\n\
         \x20       {\n\
         \x20           ErrorObj preview_error = PopLastError();\n\
         \x20           Print( string( \"ALAS_OPENVSP_PREVIEW_WARNING: \" ) + preview_error.GetErrorString() );\n\
         \x20       }\n\
         \x20       }\n\
         \x20       else\n\
         \x20       {\n\
         \x20           Print( string( \"ALAS_OPENVSP_PREVIEW_UNAVAILABLE: runtime has no graphics-capable GUI build\\n\" ) );\n\
         \x20       }\n\
         \x20       Print( string( \"ALAS_OPENVSP_EXPORT_COMPLETE\\n\" ) );\n\
         \x20       return 0;\n\
         \x20   }\n\
         \x20   return 1;\n\
         }\n",
    );
    script
}

pub(super) fn set_parm(script: &mut String, id: &str, name: &str, group: &str, value: f64) {
    let _ = writeln!(
        script,
        "    SetParmVal( {id}, \"{name}\", \"{group}\", {value:.12} );"
    );
}

pub(super) fn set_xsec_parm(script: &mut String, xsec_id: &str, name: &str, value: f64) {
    let _ = writeln!(
        script,
        "    SetParmVal( GetXSecParm( {xsec_id}, \"{name}\" ), {value:.12} );"
    );
}

pub(super) fn script_string(value: &str) -> String {
    value
        .chars()
        .map(|character| match character {
            '\\' => '/',
            '"' | '\n' | '\r' => '_',
            other if other.is_ascii() => other,
            _ => '_',
        })
        .collect()
}
