// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Marcos Quiroga Rodriguez

// Ported from alas/physics/mses_analysis.py
// Reference: alas @ rust-port-baseline.

//! MSES two-dimensional airfoil analysis: a viscous/inviscid coupled solve run
//! on the optimized design's root section for the model-comparison view.
//!
//! MSES (Mark Drela, MIT) is an external compiled tool, not a library. This
//! module drives it the way `alas/physics/mses_analysis.py` does -- through
//! native aerodynamic model's own `mset`/`mses`/`mplot` keystroke choreography, reproduced
//! here in [`driver::Mses`] -- and it is P9 rather than P5 for that reason: the
//! numbers come out of a binary, not out of arithmetic this crate performs.
//! The `exact` tier holds because MSES is deterministic: an identical mesh and
//! `mses.case` deck produce byte-identical output, so a Rust-built deck driving
//! the same binary reproduces the same result. What the parity test checks at
//! `exact` is the orchestration and the parsing, against a fixture generated by
//! running the reference through the same binaries.
//!
//! Two entry points, and they are not one function with different arguments.
//! [`run_mses_polar`] sweeps a bracket of angles and returns the scalar polar
//! ([`MsesPolarResult`]); [`run_mses_pressure_distribution`] solves one point
//! and returns the surface pressure and Mach distribution plus the flowfield
//! ([`MsesPressureResult`]), retrying at nearby angles because a single point
//! has no adjacent sweep step to fall back on. Neither ever returns an error:
//! a failure is reported through the result's `status`/`error` so a pipeline
//! run does not abort because one (possibly optimizer-degenerate) section would
//! not converge.
//!
//! Two scope decisions relative to the reference. Upstream resolves the tool
//! directory itself, through `alas/paths.py`'s frozen-build-aware resolver;
//! that is `alas-app::paths`' concern (P10, above this crate), so the entry
//! points here take the resolved directory as an argument, the same scoping
//! `alas-perf::build_vn_diagram` uses for the one field it reads off its
//! airplane. And upstream's `repo_root` argument, retained there only for
//! signature compatibility, is dropped.

include!("mses_parts/part_01.rs");
include!("mses_parts/part_02.rs");
