// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Marcos Quiroga Rodriguez

// Ported from alas/physics/mses_analysis.py
// Reference: alas @ rust-port-baseline.

//! MSES two-dimensional airfoil analysis: a viscous/inviscid coupled solve run
//! on the optimized design's root section for the model-comparison view.
//!
//! MSES (Mark Drela, MIT) is an external compiled tool, not a library. This
//! module drives it the way `alas/physics/mses_analysis.py` does -- through
//! native aerodynamic model's own `mset`/`mses`/`mplot` keystroke choreography, reproduced
//! here in [`driver::Mses`] -- and it is P9 rather than P5 for that reason: the
//! numbers come out of a binary, not out of arithmetic this crate performs.
//! The `exact` tier holds because MSES is deterministic: an identical mesh and
//! `mses.case` deck produce byte-identical output, so a Rust-built deck driving
//! the same binary reproduces the same result. What the parity test checks at
//! `exact` is the orchestration and the parsing, against a fixture generated by
//! running the reference through the same binaries.
//!
//! Two entry points, and they are not one function with different arguments.
//! [`run_mses_polar`] sweeps a bracket of angles and returns the scalar polar
//! ([`MsesPolarResult`]); [`run_mses_pressure_distribution`] solves one point
//! and returns the surface pressure and Mach distribution plus the flowfield
//! ([`MsesPressureResult`]), retrying at nearby angles because a single point
//! has no adjacent sweep step to fall back on. Neither ever returns an error:
//! a failure is reported through the result's `status`/`error` so a pipeline
//! run does not abort because one (possibly optimizer-degenerate) section would
//! not converge.
//!
//! Two scope decisions relative to the reference. Upstream resolves the tool
//! directory itself, through `alas/paths.py`'s frozen-build-aware resolver;
//! that is `alas-app::paths`' concern (P10, above this crate), so the entry
//! points here take the resolved directory as an argument, the same scoping
//! `alas-perf::build_vn_diagram` uses for the one field it reads off its
//! airplane. And upstream's `repo_root` argument, retained there only for
//! signature compatibility, is dropped.

mod deck;
mod driver;
mod exec;
mod parse;

pub use driver::Mses;

use std::path::Path;

use alas_config::MsesConfig;
use alas_geom::aircraft::airfoil::Airfoil;
use alas_geom::aircraft::spacing::linspace;

/// The repanel density both entry points fix at their MSES call sites --
/// `airfoil.repanel(n_points_per_side=80)`.
const N_POINTS_PER_SIDE: usize = 80;

/// The retry offsets `run_mses_pressure_distribution` brackets a fixed point
/// with when the exact requested angle does not converge, in degrees.
const DEFAULT_RETRY_OFFSETS_DEG: [f64; 5] = [0.0, 0.5, -0.5, 1.0, -1.0];

/// Whether an MSES run produced a usable result.
///
/// The execution and installation states exposed by an MSES run.
///
/// The reference result only had `not_run`, `ok`, and `error`. The additional
/// states are native boundary diagnostics: they preserve the reference result
/// shape while making an optional external-tool failure actionable instead of
/// presenting every problem as a solver divergence.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum MsesStatus {
    /// No run has been attempted.
    #[default]
    NotRun,
    /// MSES was disabled in configuration.
    Disabled,
    /// No MSES directory was found.
    Absent,
    /// An MSES directory exists but is missing one or more programs.
    Incomplete,
    /// A required MSES program could not be started.
    LaunchFailure,
    /// A required MSES program exceeded its configured timeout.
    Timeout,
    /// MSES exited, but its output was missing or malformed.
    ParseFailure,
    /// The run converged and its result is populated.
    Ok,
    /// At least one requested polar point converged, but the sweep is incomplete.
    PartialConvergence,
    /// The solver ran but did not produce a converged result.
    Error,
}

impl MsesStatus {
    /// The stable status string used by result consumers and diagnostics.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::NotRun => "not_run",
            Self::Disabled => "disabled",
            Self::Absent => "absent",
            Self::Incomplete => "incomplete",
            Self::LaunchFailure => "launch_failure",
            Self::Timeout => "timeout",
            Self::ParseFailure => "parse_failure",
            Self::Ok => "ok",
            Self::PartialConvergence => "partial_convergence",
            Self::Error => "error",
        }
    }
}

/// The outcome reported by MSES for one requested polar angle.
///
/// This is deliberately separate from [`MsesStatus`]. The latter describes the
/// sweep as a whole, while this preserves which exact request produced the
/// solver transcript that establishes the whole-sweep verdict.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MsesPolarPointStatus {
    /// MSES printed its normal tolerance-convergence marker for this angle.
    Converged,
    /// MSES completed its run but did not print the convergence marker.
    NotConverged,
}

impl MsesPolarPointStatus {
    /// Stable diagnostic string for persisted run evidence.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Converged => "converged",
            Self::NotConverged => "not_converged",
        }
    }
}

/// Solver evidence retained for one requested polar angle.
///
/// `solver_output` is MSES's normalized stdout, captured before the driver
/// decides whether to reinitialize the mesh. It is intentionally not parsed
/// into an invented aerodynamic diagnosis: absence of MSES's documented
/// "Converged on tolerance" marker is the only solver conclusion this driver
/// makes. Consumers can therefore inspect the numerical transcript without
/// confusing a failed nonlinear solve with a physical coefficient.
#[derive(Debug, Clone, PartialEq)]
pub struct MsesPolarPointDiagnostic {
    /// The requested angle of attack, in degrees.
    pub requested_alpha_deg: f64,
    /// MSES's convergence outcome for this request.
    pub status: MsesPolarPointStatus,
    /// Verbatim normalized MSES stdout for this requested point.
    pub solver_output: String,
}

/// The result of an MSES alpha sweep on one section.
///
/// The coefficient arrays are parallel and hold one entry per angle that
/// converged; the four `cd*` fields, the moment and the two transition
/// stations follow upstream's `MSESPolarResult` field for field. Lower-cased
/// (`cl`, not `CL`) to satisfy Rust naming; they are the standard lift, drag
/// and moment coefficients.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct MsesPolarResult {
    /// Stable status string for this result.
    pub status: MsesStatus,
    /// A human-readable reason when `status` is not successful.
    pub error: Option<String>,
    /// The section's name, or `"optimized_root_section"` when it had none.
    pub airfoil_name: String,
    /// The freestream Mach number the sweep ran at.
    pub mach: f64,
    /// The chord-referenced Reynolds number the sweep ran at.
    pub reynolds: f64,
    /// Number of operating points requested from the external solver.
    pub requested_alpha_count: usize,
    /// Number of requested operating points that converged and were parsed.
    pub converged_alpha_count: usize,
    /// One solver transcript for each requested polar point reached by MSES.
    ///
    /// An incomplete sweep retains non-converged points here even though its
    /// coefficient arrays contain only converged points. This makes the
    /// partial-convergence verdict auditable without fabricating coefficients.
    pub point_diagnostics: Vec<MsesPolarPointDiagnostic>,
    /// The angle of attack of each converged point, in degrees.
    pub alpha_deg: Vec<f64>,
    /// Lift coefficient at each converged point.
    pub cl: Vec<f64>,
    /// Total drag coefficient at each converged point.
    pub cd: Vec<f64>,
    /// Pitching-moment coefficient at each converged point.
    pub cm: Vec<f64>,
    /// Viscous drag coefficient at each converged point.
    pub cdv: Vec<f64>,
    /// Wave drag coefficient at each converged point.
    pub cdw: Vec<f64>,
    /// Upper-surface transition station (x/c) at each converged point.
    pub xtr_top: Vec<f64>,
    /// Lower-surface transition station (x/c) at each converged point.
    pub xtr_bot: Vec<f64>,
}

impl MsesPolarResult {
    /// Whether the result contains converged points that consumers may inspect.
    pub fn has_usable_data(&self) -> bool {
        matches!(self.status, MsesStatus::Ok | MsesStatus::PartialConvergence)
            && self.converged_alpha_count > 0
            && self.has_valid_coefficient_schema()
    }

    /// Check the public polar schema before a consumer uses coefficient data.
    ///
    /// The live MPlot driver validates this schema while accumulating rows.
    /// Keeping the same guard on the result object protects deserialized or
    /// manually assembled results as well: a status/count pair must not make
    /// fabricated zeros, ragged columns, or NaNs look usable.
    fn has_valid_coefficient_schema(&self) -> bool {
        let expected_len = self.converged_alpha_count;
        let columns = [
            &self.alpha_deg,
            &self.cl,
            &self.cd,
            &self.cm,
            &self.cdv,
            &self.cdw,
            &self.xtr_top,
            &self.xtr_bot,
        ];
        columns.iter().all(|column| {
            column.len() == expected_len && column.iter().all(|value| value.is_finite())
        })
    }

    /// Whether every requested operating point converged.
    pub fn is_complete(&self) -> bool {
        self.status == MsesStatus::Ok
            && self.requested_alpha_count > 0
            && self.converged_alpha_count == self.requested_alpha_count
            && self.has_valid_coefficient_schema()
    }

    /// Requested angles at which MSES did not report tolerance convergence.
    pub fn nonconverged_alpha_deg(&self) -> Vec<f64> {
        self.point_diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.status == MsesPolarPointStatus::NotConverged)
            .map(|diagnostic| diagnostic.requested_alpha_deg)
            .collect()
    }

    /// The lift-to-drag ratio at each point, `0.0` where drag is negligible --
    /// upstream's `l_over_d` property.
    pub fn l_over_d(&self) -> Vec<f64> {
        self.cl
            .iter()
            .zip(&self.cd)
            .map(|(&cl, &cd)| if cd > 1e-9 { cl / cd } else { 0.0 })
            .collect()
    }

    fn into_error(self, message: String) -> Self {
        self.into_failure(MsesStatus::Error, message)
    }

    fn into_failure(mut self, status: MsesStatus, message: String) -> Self {
        self.status = status;
        self.error = Some(message);
        self
    }
}

/// Surface pressure and local Mach at one angle, split by surface, plus the
/// flowfield Mach contour points and the panelled outline they are drawn over.
///
/// The upper/lower arrays are each ordered by x/c with wake points excluded.
/// Surface assignment follows the reference MSES analysis contract exactly:
/// points with `y >= 0` are upper-surface samples and points with `y < 0` are
/// lower-surface samples. `airfoil_x`/`airfoil_y` are the exact panelled
/// geometry MSES solved, so a contour plot's outline matches its flowfield.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct MsesPressureResult {
    /// Stable status string for this result.
    pub status: MsesStatus,
    /// A human-readable reason when `status` is not successful.
    pub error: Option<String>,
    /// The angle that actually converged -- the requested one, or a retry
    /// offset if the exact angle did not converge.
    pub alpha_deg: f64,
    /// Upper-surface x/c stations, ascending.
    pub x_upper: Vec<f64>,
    /// Upper-surface pressure coefficient at each `x_upper`.
    pub cp_upper: Vec<f64>,
    /// Upper-surface local Mach at each `x_upper`.
    pub mach_upper: Vec<f64>,
    /// Lower-surface x/c stations, ascending.
    pub x_lower: Vec<f64>,
    /// Lower-surface pressure coefficient at each `x_lower`.
    pub cp_lower: Vec<f64>,
    /// Lower-surface local Mach at each `x_lower`.
    pub mach_lower: Vec<f64>,
    /// Flowfield sample x coordinates (for Mach contours).
    pub field_x: Vec<f64>,
    /// Flowfield sample y coordinates.
    pub field_y: Vec<f64>,
    /// Flowfield local Mach at each sample.
    pub field_mach: Vec<f64>,
    /// Starting sample index of each structured `mplot` flow-field row.
    ///
    /// Blank lines in option 11 separate constant-grid-index rows. Keeping
    /// those boundaries allows the report layer to fill the native solver
    /// cells instead of reducing the field to disconnected point markers.
    pub field_row_offsets: Vec<usize>,
    /// The panelled section's x coordinates (the shape MSES actually solved).
    pub airfoil_x: Vec<f64>,
    /// The panelled section's y coordinates.
    pub airfoil_y: Vec<f64>,
    /// Verbatim `mplot` option-12 boundary-layer export used for this result.
    ///
    /// Retaining the source table makes the plotted surface distributions
    /// independently replayable instead of leaving only derived arrays after
    /// the temporary solver directory is removed.
    pub raw_bl_dump: String,
    /// Verbatim `mplot` option-11 flow-field export used for this result.
    ///
    /// This preserves the solver grid and every exported column for later
    /// contour reconstruction and parser audits.
    pub raw_flowfield_dump: String,
}

/// The physical extent of the MPlot option-11 flow-field samples.
///
/// MSET derives its outer grid from the section and its grid controls. The
/// resulting far-field extent is therefore evidence in the solver output, not
/// a UI guess or a separate contour-plot setting.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct MsesFlowfieldDomain {
    /// Minimum chord-normalized streamwise coordinate.
    pub x_min: f64,
    /// Maximum chord-normalized streamwise coordinate.
    pub x_max: f64,
    /// Minimum chord-normalized normal coordinate.
    pub y_min: f64,
    /// Maximum chord-normalized normal coordinate.
    pub y_max: f64,
}

/// Why retained `mplot` option-11/12 tables could not be replayed.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum MsesRawExportError {
    /// The boundary-layer table had no parseable numeric panel rows.
    #[error("BL dump file was empty or unparseable")]
    EmptyBoundaryLayer,
    /// MPlot did not provide both topological surface walks.
    #[error("BL dump did not contain two MPlot surface walks")]
    MissingSurfaceTopology,
}

impl MsesPressureResult {
    /// Return the actual finite domain exported by MPlot option 11.
    pub fn flowfield_domain(&self) -> Option<MsesFlowfieldDomain> {
        let mut points = self
            .field_x
            .iter()
            .zip(&self.field_y)
            .zip(&self.field_mach)
            .filter_map(|((&x, &y), &mach)| {
                (x.is_finite() && y.is_finite() && mach.is_finite()).then_some((x, y))
            });
        let (first_x, first_y) = points.next()?;
        let mut domain = MsesFlowfieldDomain {
            x_min: first_x,
            x_max: first_x,
            y_min: first_y,
            y_max: first_y,
        };
        for (x, y) in points {
            domain.x_min = domain.x_min.min(x);
            domain.x_max = domain.x_max.max(x);
            domain.y_min = domain.y_min.min(y);
            domain.y_max = domain.y_max.max(y);
        }
        Some(domain)
    }

    /// Rebuild a pressure result directly from retained raw `mplot` exports.
    ///
    /// Live execution and offline figure audits share this parser, so a
    /// report replay cannot silently reinterpret the solver tables differently
    /// from the pipeline run that originally produced them.
    pub fn replay_raw_exports(
        alpha_deg: f64,
        bl_dump: String,
        flowfield_dump: String,
        airfoil_coordinates: &[(f64, f64)],
    ) -> Result<Self, MsesRawExportError> {
        let (xs, ys, _arc_lengths, cps, mes) = parse::parse_bl_dump(&bl_dump);
        if xs.is_empty() {
            return Err(MsesRawExportError::EmptyBoundaryLayer);
        }

        let mut upper: Vec<(f64, f64, f64)> = Vec::new();
        let mut lower: Vec<(f64, f64, f64)> = Vec::new();
        for ((&x, &y), (&cp, &mach)) in xs.iter().zip(&ys).zip(cps.iter().zip(&mes)) {
            if !(-0.01..=1.02).contains(&x) {
                continue;
            }
            if y >= 0.0 {
                upper.push((x, cp, mach));
            } else {
                lower.push((x, cp, mach));
            }
        }
        if upper.is_empty() || lower.is_empty() {
            return Err(MsesRawExportError::MissingSurfaceTopology);
        }
        upper.sort_by(|a, b| a.0.total_cmp(&b.0));
        lower.sort_by(|a, b| a.0.total_cmp(&b.0));

        let (field_x, field_y, field_mach, field_row_offsets) =
            parse::parse_flowfield(&flowfield_dump);

        Ok(Self {
            status: MsesStatus::Ok,
            alpha_deg,
            x_upper: upper.iter().map(|point| point.0).collect(),
            cp_upper: upper.iter().map(|point| point.1).collect(),
            mach_upper: upper.iter().map(|point| point.2).collect(),
            x_lower: lower.iter().map(|point| point.0).collect(),
            cp_lower: lower.iter().map(|point| point.1).collect(),
            mach_lower: lower.iter().map(|point| point.2).collect(),
            field_x,
            field_y,
            field_mach,
            field_row_offsets,
            airfoil_x: airfoil_coordinates.iter().map(|point| point.0).collect(),
            airfoil_y: airfoil_coordinates.iter().map(|point| point.1).collect(),
            raw_bl_dump: bl_dump,
            raw_flowfield_dump: flowfield_dump,
            ..Self::default()
        })
    }

    fn into_error(self, message: String) -> Self {
        self.into_failure(MsesStatus::Error, message)
    }

    fn into_failure(mut self, status: MsesStatus, message: String) -> Self {
        self.status = status;
        self.error = Some(message);
        self
    }
}

/// Run an MSES alpha sweep on `airfoil`, bracketing `trim_alpha_deg`.
///
/// The section is repaneled to [`N_POINTS_PER_SIDE`] points per side, the sweep
/// spans `[trim - halfwidth, trim + halfwidth]` at the configured point count
/// (both floored, as upstream floors them at 0.5 deg and 3 points), and each
/// point is solved through the `mset`/`mses`/`mplot` sequence [`Mses`] drives.
/// `mses_dir` is the resolved folder holding the three executables.
pub fn run_mses_polar(
    airfoil: &Airfoil,
    mach: f64,
    reynolds: f64,
    trim_alpha_deg: f64,
    config: &MsesConfig,
    mses_dir: &Path,
) -> MsesPolarResult {
    let base = MsesPolarResult {
        airfoil_name: display_name(airfoil),
        mach,
        reynolds,
        ..MsesPolarResult::default()
    };
    if !config.enabled {
        return base.into_failure(
            MsesStatus::Disabled,
            "MSES analysis is disabled in configuration".to_owned(),
        );
    }
    let repaneled = match airfoil.repanel(N_POINTS_PER_SIDE) {
        Ok(repaneled) => repaneled,
        Err(error) => return base.into_error(error.to_string()),
    };
    let half = config.alpha_sweep_halfwidth_deg.max(0.5);
    let count = config.alpha_sweep_n_points.max(3) as usize;
    let alphas = linspace(trim_alpha_deg - half, trim_alpha_deg + half, count);
    Mses::new(repaneled, config, mses_dir).polar(&alphas, reynolds, mach)
}

/// Solve one MSES operating point and read back its surface pressure and Mach
/// distribution.
///
/// Retries at [`DEFAULT_RETRY_OFFSETS_DEG`] around `alpha_deg` (or the caller's
/// offsets) with a fresh mesh each attempt, since a fixed point has no adjacent
/// sweep step to continue from; the converged angle is reported back in the
/// result. `mses_dir` is the resolved folder holding the three executables.
pub fn run_mses_pressure_distribution(
    airfoil: &Airfoil,
    mach: f64,
    reynolds: f64,
    alpha_deg: f64,
    config: &MsesConfig,
    mses_dir: &Path,
    retry_offsets_deg: Option<&[f64]>,
) -> MsesPressureResult {
    let base = MsesPressureResult {
        alpha_deg,
        ..MsesPressureResult::default()
    };
    if !config.enabled {
        return base.into_failure(
            MsesStatus::Disabled,
            "MSES analysis is disabled in configuration".to_owned(),
        );
    }
    let repaneled = match airfoil.repanel(N_POINTS_PER_SIDE) {
        Ok(repaneled) => repaneled,
        Err(error) => return base.into_error(error.to_string()),
    };
    let offsets = retry_offsets_deg.unwrap_or(&DEFAULT_RETRY_OFFSETS_DEG);
    Mses::new(repaneled, config, mses_dir).pressure(alpha_deg, reynolds, mach, offsets)
}

/// A section's name, or the placeholder upstream uses when it has none.
fn display_name(airfoil: &Airfoil) -> String {
    if airfoil.name.is_empty() {
        "optimized_root_section".to_owned()
    } else {
        airfoil.name.clone()
    }
}

/// Classify the required MSES installation before attempting a process spawn.
pub(crate) fn installation_status(directory: &Path) -> Option<MsesStatus> {
    if !directory.is_dir() {
        return Some(MsesStatus::Absent);
    }
    let missing = ["mset.exe", "mses.exe", "mplot.exe"]
        .iter()
        .filter(|name| !directory.join(name).is_file())
        .copied()
        .collect::<Vec<_>>();
    if missing.is_empty() {
        None
    } else {
        Some(MsesStatus::Incomplete)
    }
}

#[cfg(test)]
mod raw_export_tests {
    use super::*;

    #[test]
    fn retained_mplot_tables_replay_the_live_parser_contract() -> Result<(), MsesRawExportError> {
        let bl = "# x y s b0 Cp Ue rho Me\n\
                  0.2 0.1 0.2 0 -0.8 0 0 1.2\n\
                  0.8 0.1 0.8 0 -0.4 0 0 1.1\n\
                  0.3 -0.1 0.3 0 0.2 0 0 0.7\n\
                  1.2 -0.1 1.2 0 0.1 0 0 0.8\n"
            .to_owned();
        let flow = "# x y rho p u v q M Cp\n\
                    0.0 -0.5 1 1 1 0 1 0.7 0\n\
                    1.0 -0.5 1 1 1 0 1 0.8 0\n\n\
                    0.0 0.5 1 1 1 0 1 0.9 0\n\
                    1.0 0.5 1 1 1 0 1 1.0 0\n"
            .to_owned();
        let result = MsesPressureResult::replay_raw_exports(
            2.5,
            bl.clone(),
            flow.clone(),
            &[(0.0, 0.0), (1.0, 0.0)],
        )?;

        assert_eq!(result.status, MsesStatus::Ok);
        assert_eq!(result.x_upper, vec![0.2, 0.8]);
        assert_eq!(result.cp_upper, vec![-0.8, -0.4]);
        assert_eq!(result.x_lower, vec![0.3]);
        assert_eq!(result.field_row_offsets, vec![0, 2]);
        assert_eq!(result.raw_bl_dump, bl);
        assert_eq!(result.raw_flowfield_dump, flow);
        Ok(())
    }

    #[test]
    fn a_missing_optional_flowfield_keeps_the_surface_solution() -> Result<(), MsesRawExportError> {
        let bl = "0.2 0.1 0.2 0 -0.8 0 0 1.2\n\
                  0.3 -0.1 0.1 0 0.2 0 0 0.7\n"
            .to_owned();
        let result = MsesPressureResult::replay_raw_exports(
            1.0,
            bl,
            String::new(),
            &[(0.0, 0.0), (1.0, 0.0)],
        )?;

        assert_eq!(result.status, MsesStatus::Ok);
        assert_eq!(result.cp_upper, vec![-0.8]);
        assert_eq!(result.cp_lower, vec![0.2]);
        assert!(result.field_x.is_empty());
        Ok(())
    }

    #[test]
    fn surface_assignment_matches_reference_y_sign_and_sorts_x() -> Result<(), MsesRawExportError> {
        let bl = "0.0 -0.002 0.0 0 1.2 0 0 0.1\n\
                  0.4 0.050 0.4 0 -0.9 0 0 1.2\n\
                  0.9 -0.010 0.9 0 -0.2 0 0 0.8\n\
                  0.0 -0.002 0.0 0 1.2 0 0 0.1\n\
                  0.4 -0.040 0.4 0 0.3 0 0 0.7\n\
                  0.9 0.020 0.9 0 0.1 0 0 0.9\n"
            .to_owned();
        let result = MsesPressureResult::replay_raw_exports(
            1.0,
            bl,
            String::new(),
            &[(1.0, -0.01), (0.0, 0.0), (1.0, 0.02)],
        )?;

        assert_eq!(result.x_upper, vec![0.4, 0.9]);
        assert_eq!(result.mach_upper, vec![1.2, 0.9]);
        assert_eq!(result.x_lower, vec![0.0, 0.0, 0.4, 0.9]);
        assert_eq!(result.mach_lower, vec![0.1, 0.1, 0.7, 0.8]);
        Ok(())
    }

    #[test]
    fn flowfield_domain_uses_every_finite_mplot_sample() {
        let result = MsesPressureResult {
            field_x: vec![-2.0, 0.5, 3.0, f64::NAN],
            field_y: vec![-1.5, 0.0, 2.0, 10.0],
            field_mach: vec![0.2, 0.8, 1.1, 0.5],
            ..MsesPressureResult::default()
        };

        assert_eq!(
            result.flowfield_domain(),
            Some(MsesFlowfieldDomain {
                x_min: -2.0,
                x_max: 3.0,
                y_min: -1.5,
                y_max: 2.0,
            })
        );
    }
}

#[cfg(test)]
mod polar_diagnostic_tests {
    use super::*;

    fn complete_polar() -> MsesPolarResult {
        MsesPolarResult {
            status: MsesStatus::Ok,
            requested_alpha_count: 1,
            converged_alpha_count: 1,
            alpha_deg: vec![1.0],
            cl: vec![0.5],
            cd: vec![0.03],
            cm: vec![-0.02],
            cdv: vec![0.02],
            cdw: vec![0.01],
            xtr_top: vec![0.4],
            xtr_bot: vec![0.6],
            ..MsesPolarResult::default()
        }
    }

    #[test]
    fn usable_polar_requires_aligned_finite_coefficient_columns() {
        let complete = complete_polar();
        assert!(complete.has_usable_data());

        let mut ragged = complete.clone();
        ragged.cdw.clear();
        assert!(!ragged.has_usable_data());
        assert!(!ragged.is_complete());

        let mut nonfinite = complete;
        nonfinite.cl[0] = f64::NAN;
        assert!(!nonfinite.has_usable_data());
    }

    #[test]
    fn partial_polar_retains_the_exact_nonconverged_requests() {
        let result = MsesPolarResult {
            requested_alpha_count: 3,
            converged_alpha_count: 1,
            point_diagnostics: vec![
                MsesPolarPointDiagnostic {
                    requested_alpha_deg: -1.0,
                    status: MsesPolarPointStatus::Converged,
                    solver_output: "Converged on tolerance".to_owned(),
                },
                MsesPolarPointDiagnostic {
                    requested_alpha_deg: 0.0,
                    status: MsesPolarPointStatus::NotConverged,
                    solver_output: "Newton iteration stopped".to_owned(),
                },
                MsesPolarPointDiagnostic {
                    requested_alpha_deg: 1.0,
                    status: MsesPolarPointStatus::NotConverged,
                    solver_output: "Newton iteration stopped".to_owned(),
                },
            ],
            ..MsesPolarResult::default()
        };

        assert_eq!(result.nonconverged_alpha_deg(), vec![0.0, 1.0]);
        assert_eq!(result.point_diagnostics[1].status.as_str(), "not_converged");
        assert_eq!(
            result.point_diagnostics[1].solver_output,
            "Newton iteration stopped"
        );
    }
}
